---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: false
    channel: "eslint-4"
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.es6"
exclude_paths:
- "db/"
- "spec/"
- "vendor/"
- "app/assets/images/"
- "app/assets/javascripts/vendor/src/"
- "app/assets/stylesheets/vendor/"


